### ISSUE TITLE
July updates

### ISSUE THREAD

**Issue by Robbbert** [HackAndPwn/Windows-7-Patching#4]
Hi there again.

I don't mean to be pushy or impatient, BUT... I wonder if the July updates can be put up as I'd like to update around a dozen computers this weekend.

Thanks for all your work.

**Comment by HackAndPwn** [comment]
Patches Uploaded and SXS registry keys added.  I have not had time to fully test these updates yet, nor have I had a chance to update the website, but you should be able to use these new files exactly like last month.

**Comment by Robbbert** [comment]
Thank you for your time. I've never tried SXS registry keys before, I assume I apply them just like any other registry change? (double-click on the .reg file)

**Comment by HackAndPwn** [comment]
Yes, apply the cumulative update, let it fail, double click to import the reg key, and the update will succeed on the next try.

**Comment by Robbbert** [comment]
Ah ok i would not have guessed that. Thanks for the info.

**Comment by HackAndPwn** [comment]
https://hackandpwn.com/windows-7-esu-analysis-updates/

**Comment by Robbbert** [comment]
Thanks for explaining it, but...

as it happened, I didn't need to do any of those registry things, I just applied the usual patches (June SSU, July main and July NET) to about 15 computers and everything was successful.

I don't bother with the NET 4.8 updates because they have never worked (for me).
