### ISSUE TITLE
KB5040497 not installed

### ISSUE THREAD

**Issue by bt4ibwem8** [HackAndPwn/Windows-7-Patching#5]
![image](https://github.com/user-attachments/assets/cefa38b5-7810-4360-817e-9b798df23c53)

this error window appears after i try to install it... KB3020369 installed OK, i applied 2 .reg files and manifest file. However i get this error in terminal for `icacls C:\Windows\WinSxS\Manifests /setowner “NT SERVICE\TrustedInstaller”`: Invalid parameter "SERVICE\TrustedInstaller""
Dunno if this error is the cause of update not installing or there is something other...

**Comment by HackAndPwn** [comment]
Did you apply the latest SSU and reboot first?

**Comment by bt4ibwem8** [comment]
KB4528069 and KB5039339 are installed. I just sucessfully installed the new KB5041838 rollup so i think i do not need KB5040497 anymore if all patches are included in the new one...

**Comment by bt4ibwem8** [comment]
Should i see `TrustedInstaller` for `winsxs` folder in `Properties/Security/Group or user names` ? Owner is TrustedInstaller but it is listed in `Group or user names` tab only for some subfolders in `winsxs` folder. I may have screwed up some things so figuring out to put it into default state.
For `sfc /scannow` I get this error:  **Verification 100% complete. Windows Resource Protection found corrupt files but was unable to fix some of them. Details are included in the CBS.Log windir\Logs\CBS\CBS.log.**
So i have suspicion it is related to winsxs folder, because i see something around this folder in CBS.log

**Comment by HackAndPwn** [comment]
Try

`dism /online /Cleanup-image /scanhealth`
`dism /online /Cleanup-image /restorehealth`

**Comment by raddyst** [comment]
> /restorehealth

This parameter for Windows 8+

**Comment by bt4ibwem8** [comment]
`/restorehealth` does not work in win7 and `/scanhealth` gives me output: The operation completed successfully.

**Comment by raddyst** [comment]
> and `/scanhealth` gives me output: The operation completed successfully.

What's written in   c:\Windows\Logs\CBS\CheckSUR.log ?

**Comment by bt4ibwem8** [comment]
Checking System Update Readiness.
Binary Version 6.1.7601.24499
2024-08-25 10:48

Checking Windows Servicing Packages

Checking Package Manifests and Catalogs

Checking Package Watchlist

Checking Component Watchlist

Checking Packages

Checking Component Store

Summary:
Seconds executed: 62
 No errors detected

**Comment by bt4ibwem8** [comment]
![image](https://github.com/user-attachments/assets/28f7aa20-eafb-4cb2-b052-cdbff6b4ba6f)

This error is my main issue when opening some software. Also i get this error when i try to run "The Windows experience index". Should be this dll inside system32 by default on Windows 7? I downloaded it and put it there. But without it some software does complain about this dll missing...

**Comment by raddyst** [comment]
> This error is my main issue when opening some software.

Which version do you use?

> Should be this dll inside system32 by default on Windows 7?

No, this .dll only for win10+ - https://learn.microsoft.com/en-us/uwp/win32-and-com/win32-apis#apis-from-api-ms-win-core-heap-l2-1-0dll

> because other people with win7 run it fine...

They may be using an old version of this software.

**Comment by bt4ibwem8** [comment]
> Which version do you 

if you mean Arsenal, the latest one...

> They may be using an old version of this software.

no, there is something broken on my system. The same apply for Rustdesk, others can run the latest version on win7 but i got this error.

**Comment by raddyst** [comment]
> if you mean Arsenal, the latest one...

I'm checked Arsenal Image Mounter v3.11.293 - that's software use .NET 8, first run:

![зображення](https://github.com/user-attachments/assets/fe933bac-258a-420f-be43-8a26e2830ff0)

[.NET 8 - Supported OS versions](https://github.com/dotnet/core/blob/main/release-notes/8.0/supported-os.md)

**Comment by bt4ibwem8** [comment]
i have installed .NET Desktop Runtime 8.0.8 from here: https://dotnet.microsoft.com/en-us/download/dotnet/8.0
it would probably runs fine for you if you installed it too

**Comment by bt4ibwem8** [comment]
should i have gdiplus.dll library in /system32 folder? This file is missing on my system

**Comment by HackAndPwn** [comment]
> should i have gdiplus.dll library in /system32 folder? This file is missing on my system

I don't have it on my fully patched Win7 x64 system.

**Comment by bt4ibwem8** [comment]
![image](https://github.com/user-attachments/assets/682983cd-d3be-4e3b-824b-fc54fa8c2166)

I see also other DLLs missing... Can you run Rustdesk (flutter version, not sciter) without error?

**Comment by piotr25691** [comment]
Be aware that update install failures can also occur if you've installed too many updates before proceeding with ESU installation, so ensure you've installed as little updates as possible, or integrate your updates with NTLite on a new installation image of Windows 7 Enterprise. That worked for me.

**Comment by bt4ibwem8** [comment]
@piotr25691 
I got installed all updates, except KB5042354. This one fails with both method (WU and manuall installation).

**Comment by piotr25691** [comment]
Usually it happens because the WinSxS folder has been "corrupted" which prevents ESU from installing

**Comment by HackAndPwn** [comment]
> Be aware that update install failures can also occur if you've installed too many updates before proceeding with ESU installation, so ensure you've installed as little updates as possible, or integrate your updates with NTLite on a new installation image of Windows 7 Enterprise. That worked for me.

I personally haven't experienced this, have been updating the same VM pretty much monthly for years
![image](https://github.com/user-attachments/assets/7fbd9014-b81a-4c32-9191-10d0253e5afd)

![image](https://github.com/user-attachments/assets/97774064-d3f4-406e-88b2-4900006451cf)

However I do agree, if you are starting from a clean image, skip all the cumulatives and just do the latest one.

**Comment by HackAndPwn** [comment]
> @piotr25691 I got installed all updates, except KB5042354. This one fails with both method (WU and manuall installation).

How is this update showing up for you in Windows Update?  None of the updates should be showing there following my instructions unless you have also messed with "BypassESU" utilities, which would likely explain why you are having issues.

**Comment by piotr25691** [comment]
> > @piotr25691 I got installed all updates, except KB5042354. This one fails with both method (WU and manuall installation).
> 
> 
> 
> How is this update showing up for you in Windows Update?  None of the updates should be showing there following my instructions unless you have also messed with "BypassESU" utilities, which would likely explain why you are having issues.

Yes I am using an ESU suppressor from MDL forums which enables the updates to show, and they worked for me, except .NET (that will fail)

**Comment by raddyst** [comment]
> Usually it happens because the WinSxS folder has been "corrupted" which prevents ESU from installing

> except .NET (that will fail)

KB5042354 for .net framework

**Comment by piotr25691** [comment]
> > Usually it happens because the WinSxS folder has been "corrupted" which prevents ESU from installing
> 
> 
> 
> > except .NET (that will fail)
> 
> 
> 
> KB5042354 for .net framework

This needs a [specific installer](https://forums.mydigitallife.net/threads/bypass-windows-7-extended-security-updates-eligibility.80606/page-157#post-1596676) to not receive a generic 0x80070643 (Fatal error during installation) error message.

Be aware you need to register to access the files

**Comment by raddyst** [comment]
> This needs a [specific installer](https://forums.mydigitallife.net/threads/bypass-windows-7-extended-security-updates-eligibility.80606/page-157#post-1596676) to not receive a generic 0x80070643 (Fatal error during installation) error message.

)) i'm use https://github.com/abbodi1406/dotNetFx4xW7A with updatepack.

**Comment by HackAndPwn** [comment]
> > > @piotr25691 I got installed all updates, except KB5042354. This one fails with both method (WU and manuall installation).
> > 
> > 
> > How is this update showing up for you in Windows Update?  None of the updates should be showing there following my instructions unless you have also messed with "BypassESU" utilities, which would likely explain why you are having issues.
> 
> Yes I am using an ESU suppressor from MDL forums which enables the updates to show, and they worked for me, except .NET (that will fail)

These techniques/instructions do not require any ESU suppressor for any update except for latest .NET 4.8 Cumulative on Windows 7.  As I have not found a way to install it without additional custom binaries or hacks, I am merely including it in the list to keep track of the latest updates.

These techniques/instructions also work for Windows Server 2012 R2, and Windows 8.1 (separate repository) without any ESU suppressor, including the latest cumulative .NET 4.8 package.

**Comment by HackAndPwn** [comment]
> > > > @piotr25691 I got installed all updates, except KB5042354. This one fails with both method (WU and manuall installation).
> > > 
> > > 
> > > How is this update showing up for you in Windows Update?  None of the updates should be showing there following my instructions unless you have also messed with "BypassESU" utilities, which would likely explain why you are having issues.
> > 
> > 
> > Yes I am using an ESU suppressor from MDL forums which enables the updates to show, and they worked for me, except .NET (that will fail)
> 
> These techniques/instructions do not require any ESU suppressor for any update except for latest .NET 4.8 Cumulative on Windows 7. As I have not found a way to install it without additional custom binaries or hacks, I am merely including it in the list to keep track of the latest updates.
> 
> These techniques/instructions also work for Windows Server 2012 R2, and Windows 8.1 (separate repository) without any ESU suppressor, including the latest cumulative .NET 4.8 package.

I have updated the page to include a note that about this specific update.  Thanks for the feedback!

**Comment by piotr25691** [comment]
Assuming this is what you intended, the guide lists ESUs for the people that actually want to use ESUs to update to a max. of October 2024 (extended ESU EoL for WES7-based OSs like POSReady), else you will have a final image updated to January 2020 (official EoL for retail editions of Windows 7)

**Comment by piotr25691** [comment]
> > This needs a [specific installer](https://forums.mydigitallife.net/threads/bypass-windows-7-extended-security-updates-eligibility.80606/page-157#post-1596676) to not receive a generic 0x80070643 (Fatal error during installation) error message.
> 
> 
> 
> )) i'm use https://github.com/abbodi1406/dotNetFx4xW7A with updatepack.

Does UpdatePack read it normally and use it when it is in the same folder? That could be useful to add the .NET cumulative update to an installation image

**Comment by raddyst** [comment]
> Does UpdatePack read it normally and use it when it is in the same folder? That could be useful to add the .NET cumulative update to an installation image

Of course, addon support to updatepack was implemented four years ago.

**Comment by piotr25691** [comment]
Thank you, saves me the hassle of finding a patched installer for .NET ESU

**Comment by piotr25691** [comment]
New update: Windows 7 ESU deadline extended until [January 2026](https://forums.mydigitallife.net/threads/bypass-windows-7-extended-security-updates-eligibility.80606/page-406#post-1851024)

**Comment by HackAndPwn** [comment]
> New update: Windows 7 ESU deadline extended until [January 2026](https://forums.mydigitallife.net/threads/bypass-windows-7-extended-security-updates-eligibility.80606/page-406#post-1851024)
> 
> Spoof your OS as Windows Server 2008 R2

This is what I have been doing to keep Windows 8.1 patched since the beginning of 2023 when patches stopped for that OS.

https://hackandpwn.com/windows-8.1-and-2012-r2-esu-analysis/
