### ISSUE TITLE
Servicing Stack dependency

### ISSUE THREAD

**Issue by piotr25691** [HackAndPwn/Windows-7-Patching#6]
There doesn't appear to be a Servicing Stack update installed that is not an ESU one.

Before installing ESUs, make sure you install KB4592510.
This is a prerequisite for some of the updates listed here, and they won't install without this Servicing Stack already present.

**Comment by piotr25691** [comment]
You need more updates than you listed to fully update an unmodified SP1 image.

**Comment by HackAndPwn** [comment]
I appreciate the feedback - I have incorporated both of these into a new Prerequisite section

https://github.com/HackAndPwn/HackAndPwn.github.io/commit/926b0cf0c934ce040fcbeb70050efc41b4c39703

**Comment by piotr25691** [comment]
INFO: KB4592510 is not applicable.

This may be an ESU SSU, use KB4490628.

**Comment by piotr25691** [comment]
While most of these updates will integrate fine with a tool like NTLite, KB943790 will not integrate, giving an "Operation not supported" message.

**Comment by piotr25691** [comment]
When making an image from scratch using Windows 7 Enterprise as base do this:

- Step 1: Use the updates from this repo
Download and integrate them using NTLite. Save the image.

- Step 2: Apply the Simplix UpdatePack7R2 and its .NET addon
Download the [update pack](https://majorgeeks.com/files/details/simplix_updatepack.html), and the [addon](https://github.com/abbodi1406/dotNetFx4xW7A). In an administrative CMD on an already installed Windows installation run this command: `UpdatePack7R2-24.9.10.exe /WimFile:install.wim /Index=1 /NVMe /FixOn /Optimize`
- Step 3: Apply the remainders
Mount the image with NTLite. Quit without saving. Download [the ESU patcher](https://gitlab.com/stdout12/adns/uploads/cd0a6954699d94671142986b48e593ec/Win7_WU_ESU_Patcher.7z) and apply it in `%localappdata%\Temp\NLTmpMnt01`, go back to NTLite and apply the following: KB2667402, KB2676562, KB2698365, KB2813347, KB2834140, KB2862330, KB2894844, KB3123479, KB3185319, KB5006761

Since the packages for Windows XP Mode, and SUA (Subsystem for UNIX-based applications) are EXEs, they are not supported by NTLite. KB943790 does not automatically apply with NTLite, and **WILL** require a manual installation.

By this method you can create a huge (~6GB) ISO image of Windows 7 with all updates integrated.

**Comment by raddyst** [comment]
> * Download and integrate them using NTLite. Save the image.
Why use ntlite? It's unnecessary - if updatepack is used later.

> * and the [addon](https://github.com/abbodi1406/dotNetFx4xW7A)
[DirectX](https://www.wincert.net/forum/topic/12622-microsoft-directx-end-user-runtimes-june-2010/), [Visual C++](https://gitlab.com/stdout12/adns/-/releases)

> * /NVMe
Removed parameter

> * KB2676562
Replaced by KB4015549

> * KB2813347
Replaced by KB4512506

> * KB3123479
Replaced by KB4015549

> * KB3185319
Replaced by KB3197868

> By this method you can create a huge (~6GB) ISO image of Windows 7 with all updates integrated.
Or you can use esd compression (4gb<)

**Comment by piotr25691** [comment]
> > * Download and integrate them using NTLite. Save the image.
> 
> 
> 
> Why use ntlite? It's unnecessary - if updatepack is used later.
> 
> 
> 
> > * and the [addon](https://github.com/abbodi1406/dotNetFx4xW7A)
> 
> 
> 
> [DirectX](https://www.wincert.net/forum/topic/12622-microsoft-directx-end-user-runtimes-june-2010/), [Visual C++](https://gitlab.com/stdout12/adns/-/releases)
> 
> 
> 
> > * /NVMe
> 
> 
> 
> Removed parameter
> 
> 
> 
> > * KB2676562
> 
> 
> 
> Replaced by KB4015549
> 
> 
> 
> > * KB2813347
> 
> 
> 
> Replaced by KB4512506
> 
> 
> 
> > * KB3123479
> 
> 
> 
> Replaced by KB4015549
> 
> 
> 
> > * KB3185319
> 
> 
> 
> Replaced by KB3197868
> 
> 
> 
> > By this method you can create a huge (~6GB) ISO image of Windows 7 with all updates integrated.
> 
> 
> 
> Or you can use esd compression (4gb<)

1. Windows Update has installed exactly these after I made the ISO using steps 1 and 2

2. According to MDL forums this is a valid parameter.

3. Windows 7's PE does not support ESD.

4. UpdatePack does not knock out exactly all of the updates. NTLite is used to automatically integrate certain missing updates selectively.

5. I only use Microsoft redists for DirectX, .NET, and VC++ with their corresponding unattended switches.

**Comment by raddyst** [comment]
> 1. Windows Update has installed exactly these after I made the ISO using steps 1 and 2

I don't think these are necessary updates, as the author writes, windows update can be completely disabled:
https://blog.simplix.info/updatepack7r2/comment-page-107/#comment-5499
https://blog.simplix.info/updatepack7r2/comment-page-107/#comment-5500

+ you can always compare .dll file versions after installing expired updates.

> 2. According to MDL forums this is a valid parameter.

Check list of parameters on author's site: [updatepack 20.2.21](https://web.archive.org/web/20200308213304/https://blog.simplix.info/updatepack7r2/) has a parameter /NVMe, [updatepack 20.8.13](https://web.archive.org/web/20200815142354/https://blog.simplix.info/updatepack7r2) hasn't

> 3. Windows 7's PE does not support ESD.

Yes, win8.1-10 boot.wim is used.

> 4\. UpdatePack does not knock out exactly all of the updates. NTLite is used to automatically integrate certain missing updates selectively.

Ok, but our torrent trackers really don't like Windows builds made with ntlite.

**Comment by piotr25691** [comment]
Also it appears to be that KB5006761 is an update that should be superseded by KB5041954, since they are both cumulative updates for .NET Framework, and only the current one applies.

**Comment by raddyst** [comment]
> Also it appears to be that KB5006761 is an update that should be superseded by KB5041954, since they are both cumulative updates for .NET Framework, and only the current one applies.

Yes, if you need updates for Windows Update service (removed from current versions of updatepack since 24.3.13), then their numbers:
KB2547666-x86-x64, KB2667402-v2-x86-x64, KB2698365-x86-x64, KB2732059-v5-x86-x64, KB2773072-x86-x64, KB2834140-v2-x86-x64, KB2862330-v2-x86-x64, KB2894844-x86-x64, KB2919469-x86-x64, KB2970228-x86-x64, KB2984972-x86-x64, KB3004375-v3-x86-x64, KB3006137-x86-x64, KB4575903-x86-x64

https://blog.simplix.info/update7/#24.3.13

**Comment by HackAndPwn** [comment]
> INFO: KB4592510 is not applicable. This may be an ESU SSU, use KB4490628.
> 
> KB4528069 is an eligibility testing update and shouldn't be available to a non-ESU system, unless you have already updated it to the current version

Thanks for calling the SSU issue out, this has been fixed.

Understood KB4528069 isn't required, but it was how the research/techniques first worked without any using any custom BypassEsu binaries  (https://hackandpwn.com/windows-7-esu-analysis/) so keeping for historical reference purposes.
